### ISSUE TITLE
Typechecks fail

### ISSUE THREAD

**Issue by mxstbr** [orta/github-webhook-event-types#1]
Getting these errors locally in `danger-plugin-labels`: 

![screen shot 2018-03-19 at 15 11 19](https://user-images.githubusercontent.com/7525670/37600769-8efe3324-2b88-11e8-9742-9148f32201d2.png)

If you clone the repo and revert this commit https://github.com/withspectrum/danger-plugin-labels/commit/87bfd0cc14cf8b3f216763bfcada4688ecd6dc6a you should see those errors on `yarn run build`.

**Comment by mxstbr** [comment]
Note that the plugin is based on the yeoman template for danger plugins, so I assume the same thing would happen for all plugins based on it. The plugin only did `import { Issue } from 'github-webhook-event-types'`.

**Comment by mxstbr** [comment]
Note that the plugin is based on the yeoman template for danger plugins, so I assume the same thing would happen for all plugins based on it. The plugin only did `import { Issue } from 'github-webhook-event-types'`.

**Comment by orta** [comment]
Likely improvements to the TypeScript compiler then, pretty sure I made that dependency loose
